name: Deploy myReps

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # or your required Ruby version

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Authenticate to Google Cloud
        env:
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        run: |
          echo "$GCP_SERVICE_ACCOUNT_KEY" > $HOME/gcloud-key.json
          gcloud auth activate-service-account --key-file=$HOME/gcloud-key.json
          gcloud config set project ascend-dev-c281a

      - name: Fetch secret from Google Secret Manager
        id: get_secret
        run: |
          SECRET=$(gcloud secrets versions access latest --secret=GOOGLEMAPSAPIKEY")
          echo "::set-output name=GOOGLE_API_KEY::$SECRET"

      - name: Build Jekyll site
        env:
          GOOGLE_API_KEY: ${{ steps.get_secret.outputs.GOOGLE_API_KEY }}
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
